### ISSUE TITLE
Module and database

### ISSUE THREAD

**Issue by sylvain258** [ka7eh/maplibre-gl-basemaps#2]
Bonjour,

Je travaille depuis pas mal de temps avec ce module. J'aimerais cependant l'administrer via une base de données et non en rentrant en dur l'array que demande l'attribut basemaps. 
J'ai bien essayé avec une requête AJAX qui fait appel à une table dans laquelle se trouve les couches à afficher. Je récupère correctement mon tableau. Seulement au moment où il s'agit de l'intégrer dans le module (c'est-à-dire renseigner basemaps), le module ne s'affiche pas.
Y-a t il une solution ? MErci pour votre retour
Sylvain

I've been working with this module for quite some time. However, I would like to administer it via a database and not by entering the array requested by the "basemaps" attribute. 
I tried with an AJAX request that calls a table in which the layers to be displayed are located. I get my table correctly. Only when it comes to integrate it in the module (i.e. to fill in basemaps), the module does not display.
Is there a solution? Thank you for your feedback

**Comment by ka7eh** [comment]
@sylvain258 When you say the module does not display, do you mean you're getting any error? Can you provide a simple example of your use case, with the errors you're getting?

**Comment by sylvain258** [comment]
Hello, I found a solution which is ok well. There are not errors, The solution is to call database via ajax in synchronous request. So, my problem don't come from your module but in the request. So, ajax request and put success (in the code), rather than complete. Thank you for your help. Sylvain

**Comment by sylvain258** [comment]
Hello, I have another problem with encoding image. Could you confirm me this module doesn't allow WMS layers ? I have a problem with WMS layers called with GetCapabilities request. Thank you for your feedback. Sylvain

**Comment by ka7eh** [comment]
@sylvain258 any supported source by maplibre (< v2.1.6) should work fine. This module adds whatever source you include in `basemap` option to a maplibre instance.
